version: '3'
services:
  postgres:
    container_name: task2-9-server
    restart: always
    image: "postgres:${POSTGRES_VERSION}" 
    env_file:
      - .env 
    volumes:
      - "postgres-data:/var/lib/postgresql/data/pgdata"
      - "./sqldump/:/var/sqldump/"
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  postgres2:
    container_name: task10-server
    restart: always
    image: "postgres:${POSTGRES_VERSION}" 
    env_file:
      - task10.env 
    volumes:
      - "postgres-data:/var/lib/postgresql/data/pgdata"
      - "./sqldump/:/var/sqldump/"
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
  postgres3:
    container_name: task11-server
    restart: always
    image: "postgres:${POSTGRES_VERSION}" 
    env_file:
      - task11.env 
    volumes:
      - "postgres-data:/var/lib/postgresql/data/pgdata"
      - "./sqldump/:/var/sqldump/"
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
  postgres4:
    container_name: final-server
    restart: always
    image: "postgres:${POSTGRES_VERSION}" 
    env_file:
      - final.env 
    volumes:
      - "postgres-data:/var/lib/postgresql/data/pgdata"
      - "./sqldump/:/var/sqldump/"
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${POSTGRES_USER}"
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD}"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - "./sqldump/:/var/sqldump/"
    links:
      - "postgres:pgsql-server"
volumes:
  postgres-data:
  pgadmin-data: